### ISSUE TITLE
ClassNotFoundException in MethodTracerCommandPredictor.predictMethodToken

### ISSUE THREAD

**Issue by gharrma** [google/ide-perf#20]
@josh-127 I tried to add you as the "assignee", but GitHub wouldn't let me for some reason. So tagging you here instead!

```
2020-06-25 22:20:59,582 [ 300146]  ERROR - on.CompletionProgressIndicator - com.intellij.openapi.progress.ProgressManage PluginClassLoader[com.google.ide-perf, 1.0-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@1c899759 
java.lang.ClassNotFoundException: com.intellij.openapi.progress.ProgressManage PluginClassLoader[com.google.ide-perf, 1.0-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@1c899759
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.google.idea.perf.methodtracer.MethodTracerCommandPredictor.predictMethodToken(MethodTracerCommandPredictor.kt:71)
	at com.google.idea.perf.methodtracer.MethodTracerCommandPredictor.predict(MethodTracerCommandPredictor.kt:52)
	at com.google.idea.perf.CommandCompletionProvider.fillCompletionVariants(CommandCompletionProvider.kt:70)
	at com.intellij.util.textCompletion.TextCompletionContributor.fillCompletionVariants(TextCompletionContributor.java:58)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:59)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.kt:30)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:834)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:819)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$6(CodeCompletionHandlerBase.java:332)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:324)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by josh-127** [comment]
I'll look into it. What are the steps to reproduce this exception?

**Comment by gharrma** [comment]
Invoke method-name completion for a class that does not exist:
```
trace asdf#<ctrl-space>
```

**Comment by gharrma** [comment]
(To be clear, no need to look into it today!)
